server:
  port: 9264

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountbook?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
##mybatis的原生态支持
mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.accountbook.entity
logging:
  config: classpath:config/log4j2.xml